[general]
BEEP_PAUSE = 1
ENGLISH_VOICE_LIST = "LimitedEnglishVoices.txt"
SELECTED_PITCHES = ["-2Hz", "+0Hz", "+2Hz"]
SELECTED_RATES = ["-5%", "+0%", "+5%"]
CHATUSER_CONFIG_FILE = "chatuser_config.toml"
PRESENTATION_VOICE = "en-US-AriaNeural"
PRESENTATION_PITCH = "+0Hz"
PRESENTATION_RATE = "+15%"
PRESENTATION_VOLUME = "+0%"
USER_PITCH_DEFAULT = "+0Hz"
USER_RATE_DEFAULT = "+15%"
USER_DEFAULT_VOLUME = "+0%"
BEEP_SOUND = "beep.mp3"
BEEP_RESET_DELAY = 20
TTSBOT_LOG = "ttsbot.log"
BEEP = "Enabled"
TTSCommand = "Disabled"
GAP_MONITOR = "Disabled"
GAP_LOG = "timing.log" 
STREAMID = "PCOOSewAYMc" 
TESTTIMING = "Disabled" 
[predefined_users]
# name = [TTSname,voice,rate,pitch,volume]
mbeware=["em beware","en-GB-RyanNeural","None","None","None"]
maple-circuit-live=["Maple Circuit","None","None","None","None"]
sam_m_be_silly=["Sam","None","None","+200Hz","None",]

